version: '3.6'

services:
  writetest:
    image: saimonsl/write-test:0.0.2
    environment:
      TEST_PATH: /nfs_share/test
    volumes:
      - test-docker:/nfs_share
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    healthcheck:
      disable: true

volumes:
  test-docker:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=10.0.0.49,nolock,soft,rw"
      device: ":/nfs_share/docker"
